Offer/Offer/Models/Buyer/BuyerDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Buyer
{
    public class BuyerDetailModel 
    {
        public int BuyerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public int ListingId { get; set; }
        public int BuyerGroupId { get; set; }
    
       

    }
}

Offer/Offer/Models/Buyer/NewBuyerGroupModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Buyer
{
    public class NewBuyerGroupModel 
    {
        public int BuyerGroupId { get; set; }
        public string BuyerGroupName { get; set; }
        public string AgentFirstname { get; set; }
        public string AgentLastname { get; set; }
        public string AgentEmail { get; set; }
        public string AgentPhone { get; set; }
        public int AgentUserId { get; set; }
        public decimal Target_Price { get; set; }
        public string SearchAreas { get; set; }
        public string BuyerNote { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.Guid UniqueId { get; set; }
        public int OrganizationId { get; set; }
        public List<BuyerDetailModel> BuyersList { get; set; }
       
    }
}

Offer/Offer/Models/Buyer/NewBuyerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Buyer
{
    public class NewBuyerModel 
    {
        public int BuyerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public int ListingId { get; set; }
        public int BuyerGroupId { get; set; }
        public string Note { get; set; }
    
       

    }
}

Offer/Offer/Models/Buyer/SearchBuyerGroupModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Offer.Models.Offer;


namespace Offer.Models.Buyer
{
    public class SearchBuyerGroupModel
    {
        public List<BuyerGroupItem> BuyerGroupItems { get; set; }
    }
    public class SearchBuyerModel
    {
        public List<BuyerItem> BuyerItems { get; set; }
    }
    public class BuyerGroupItem
    {
        public int BuyerGroupId { get; set; }
        public string BuyerGroupName { get; set; }
        public string AgentFirstname { get; set; }
        public string AgentLastname { get; set; }
        public string AgentEmail { get; set; }
        public string AgentPhone { get; set; }
        public int AgentUserId { get; set; }
        public decimal Target_Price { get; set; }
        public string SearchAreas { get; set; }
        public string BuyerNote { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.Guid UniqueId { get; set; }
        public int OrganizationId { get; set; }
        public List<BuyerItem> BuyersList { get; set; }
        public string Status_LookupCode { get; set; }
        public OfferGroupSearchModel OfferGroups { get; set; }
    }

    public class BuyerItem
    {
        public int BuyerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int CreatedByUserId { get; set; }
        public int ModifiedByUserId { get; set; }
        public int ListingId { get; set; }
        public int BuyerGroupId { get; set; }



    }
}

Offer/Offer/Controllers/BuyerController.cs
using Offer.Api;
using Offer.Data;
using Offer.Models.Buyer;
using Offer.Models.Offer;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OfferManagement.Mvc.Controllers
{
    public class BuyerController : Controller
    {

        OfferApiController api = new OfferApiController();
        
        // GET: Buyer
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult _DispalyBuyerGroup()
        {
            List<BuyerGroup> groups = api.GetAllBuyerGroup();
            SearchBuyerGroupModel model = new SearchBuyerGroupModel();
            model.BuyerGroupItems = new List<BuyerGroupItem>();
            foreach (BuyerGroup group in groups)
            {
                model.BuyerGroupItems.Add(new BuyerGroupItem()
                {
                    BuyerGroupId = group.BuyerGroupId,
                    BuyerGroupName = group.BuyerGroupName,
                    AgentFirstname = group.AgentFirstname,
                    AgentLastname = group.AgentLastname,
                    AgentEmail = group.AgentEmail,
                    AgentPhone = group.AgentPhone,
                    Target_Price = group.Target_Price,
                    SearchAreas = group.SearchAreas,
                    BuyerNote = group.BuyerNote,
                });

            }

            foreach (BuyerGroupItem item in model.BuyerGroupItems)
            {
                item.BuyersList = new List<BuyerItem>();
                List<Buyer> buyers = api.GetBuyerByGroupId(item.BuyerGroupId);
                foreach (var buyer in buyers)
                {
                    item.BuyersList.Add(new BuyerItem()
                    {
                        Firstname = buyer.Firstname,
                        Lastname = buyer.Lastname,
                        Email = buyer.Email,
                        Phone = buyer.Phone,
                        Address = buyer.Address,
                        City = buyer.City,
                        State = buyer.State,
                        PostalCode = buyer.PostalCode,
                    });
                }
                item.OfferGroups = new OfferGroupSearchModel();
                List<OfferGroupSummary> offerGroups = api.OfferGroupSummarySearch(item.BuyerGroupId);
                foreach (OfferGroupSummary offerGroup in offerGroups)
                {
                    item.OfferGroups.OfferGroupItems.Add(new OfferGroupGridItem()
                    {
                        AgentEmail = offerGroup.AgentEmail,
                        AgentFirstname = offerGroup.AgentFirstname,
                        AgentLastname = offerGroup.AgentLastname,
                        BuyerFirstname = offerGroup.BuyerFirstname,
                        BuyerLastname = offerGroup.BuyerLastname,
                        InternalNote = offerGroup.InternalNote,
                        //LoanType = offerGroup.LoanType != null ? offerGroup.LoanType.Value : "",
                        OfferAmount = offerGroup.OfferAmount,
                        OfferDate = offerGroup.OfferDate,
                        CounterInternalNote = offerGroup.CounterInternalNote,
                        //CounterLoanType = offerGroup.CounterLoanType != null ? offerGroup.CounterLoanType.Value : "",
                        CounterOfferAmount = offerGroup.CounterOfferAmount,
                        CounterOfferDate = offerGroup.CounterOfferDate,
                        CounterOfferId = offerGroup.CounterOfferId,
                        OfferId = offerGroup.OfferId
                    });
                }


            }

            return PartialView(model.BuyerGroupItems);
        }
      
        [HttpGet]
        public ActionResult NewBuyerGroup()
        {
            NewBuyerGroupModel model = new NewBuyerGroupModel();
            BuyerGroup bg = new BuyerGroup();
            bg.BuyerGroupName = "Your Group Name";
            //Get usder detail from session 
            //bg.AgentFirstname = Convert.ToInt32(Session["UserId"]);
            //bg.AgentLastname = CurrentUser.Lastname;           

            api.SaveBuyerGroup(bg);
             return RedirectToAction("Detail", new { id = bg.BuyerGroupId });
            
        }
        public PartialViewResult _EditBuyerGroup(int BuyerGroupId)
        {
            BuyerGroup model = api.GetBuyerGroupDetail(BuyerGroupId);
            BuyerGroupItem bg = new BuyerGroupItem();
            bg.BuyerGroupId = model.BuyerGroupId;
            bg.BuyerGroupName = model.BuyerGroupName;
            bg.AgentFirstname = model.AgentFirstname;
            bg.AgentLastname = model.AgentLastname;
            bg.AgentEmail = model.AgentEmail;
            bg.AgentPhone = model.AgentPhone;
            bg.Target_Price = model.Target_Price;
            bg.SearchAreas = model.SearchAreas;
            bg.BuyerNote = model.BuyerNote;
            return PartialView(bg);
        }
        [HttpPost]
        public ActionResult EditBuyerGroup(NewBuyerGroupModel model)
        {
            BuyerGroup bg = new BuyerGroup();
            bg.BuyerGroupId = model.BuyerGroupId;
            bg.BuyerGroupName = model.BuyerGroupName;
            bg.AgentFirstname = model.AgentFirstname;
            bg.AgentLastname = model.AgentLastname;
            bg.AgentEmail = model.AgentEmail;
            bg.AgentPhone = model.AgentPhone;
            bg.Target_Price = model.Target_Price;
            bg.SearchAreas = model.SearchAreas;
            bg.BuyerNote = model.BuyerNote;
            
            api.EditBuyerGroup(bg);

            return RedirectToAction("Detail", new { id = bg.BuyerGroupId });
        }
   
     public ActionResult Detail(int id)
        {
            BuyerGroup model = api.GetBuyerGroupDetail(id);
            BuyerGroupItem bg = new BuyerGroupItem();
            bg.BuyerGroupId = model.BuyerGroupId;
            bg.BuyerGroupName = model.BuyerGroupName;
            bg.AgentFirstname = model.AgentFirstname;
            bg.AgentLastname = model.AgentLastname;
            bg.AgentEmail = model.AgentEmail;
            bg.AgentPhone = model.AgentPhone;
            bg.Target_Price = model.Target_Price;
            bg.SearchAreas = model.SearchAreas;
            bg.BuyerNote = model.BuyerNote;
            SearchBuyerModel buyerdetail = new SearchBuyerModel();
            buyerdetail.BuyerItems = new List<BuyerItem>();
            List<Buyer> buyers = api.GetBuyerByGroupId(id);
            foreach (var buyer in buyers)
            {
                buyerdetail.BuyerItems.Add(new BuyerItem
                {
                    Firstname = buyer.Firstname,
                    Lastname = buyer.Lastname,
                    Email = buyer.Email,
                    Phone = buyer.Phone,
                    Address = buyer.Address,
                    City = buyer.City,
                    State = buyer.State,
                    PostalCode = buyer.PostalCode,
                });
            }
            OfferGroupSearchModel offerGroupSearchModel = new OfferGroupSearchModel();
            List<OfferGroupSummary> offerGroups =api.OfferGroupSummarySearch(id);
            foreach (OfferGroupSummary offerGroup in offerGroups)
            {
                offerGroupSearchModel.OfferGroupItems.Add(new OfferGroupGridItem()
                {
                    AgentEmail = offerGroup.AgentEmail,
                    AgentFirstname = offerGroup.AgentFirstname,
                    AgentLastname = offerGroup.AgentLastname,
                    BuyerFirstname = offerGroup.BuyerFirstname,
                    BuyerLastname = offerGroup.BuyerLastname,
                    InternalNote = offerGroup.InternalNote,
                    //LoanType = offerGroup.LoanType != null ? offerGroup.LoanType.Value : "",
                    OfferAmount = offerGroup.OfferAmount,
                    OfferDate = offerGroup.OfferDate,
                    CounterInternalNote = offerGroup.CounterInternalNote,
                    //CounterLoanType = offerGroup.CounterLoanType != null ? offerGroup.CounterLoanType.Value : "",
                    CounterOfferAmount = offerGroup.CounterOfferAmount,
                    CounterOfferDate = offerGroup.CounterOfferDate,
                    CounterOfferId = offerGroup.CounterOfferId,
                    OfferId = offerGroup.OfferId
                });
            }

           bg.OfferGroups = offerGroupSearchModel;
            bg.BuyersList = buyerdetail.BuyerItems;
            return View(bg);
        }
     public PartialViewResult NewBuyer(int BuyerGroupId)
     {
         TempData["BuyerGroupId"] = BuyerGroupId;
         return PartialView();
     }
     [HttpPost]
     public ActionResult NewBuyer(NewBuyerModel model)
     {
         Buyer buyer = new Buyer();
         buyer.BuyerGroupId = model.BuyerGroupId;
         buyer.Firstname = model.Firstname;
         buyer.Lastname = model.Lastname;
         buyer.Email = model.Email;
         buyer.Phone = model.Phone;
         buyer.Address = model.Address;
         buyer.City = model.City;
         buyer.State = model.State;
         buyer.PostalCode = model.PostalCode;        
         buyer.DateCreated = DateTime.Now;         
         buyer.DateModified = DateTime.Now;
        
         api.SaveBuyer(buyer);
         return RedirectToAction("Detail", new { id = model.BuyerGroupId });
     }
     public PartialViewResult _SearchResult(string SearchType, string Name)
     {
         List<Buyer> sellers;
       
         if (SearchType == "All")
         {
             if (Name != null)
             {
                 sellers = api.GetBuyerByName(Name);
             }
             else
             {
                 sellers = api.GetAllBuyerList();
             }
         }
         else if (SearchType == "Active")
         {
             if (Name != null)
             {
                 sellers = api.GetAllBuyerList();
             }
             else
             {

Offer/Offer/Views/Buyer/BuyerList.cshtml
@model List<Offer.Models.Buyer.BuyerItem>
@*<button type="button" onclick="NewSeller()" class="btn btn-outline btn-primary btn-sm">New Seller</button>*@
<div class="col-sm-12">
    <button class="btn ctaBtn btn_mainBlue  border_btn col-md-3 col-xs-12 no-padd txt-upper text-center" onclick="NewBuyer()"><i class="material-icons icon_has_topic fs-20">group_add</i><span class="topic_has_icon">New Buyer</span></button>
</div>

    @{
        int i = 1;
    }
    @foreach (var item in Model)
    {
        <div class="col-sm-6 text-center col-xs-12 marg-t-15" id="seller-@item.BuyerId">
            <div class="boxesPadding_full no-padd pull-left">
                <div class="no-padd pull-left edit ">
                    <div class="saller_img">
                        <img src="~/Content/images/demo/user.jpg" alt="">
                    </div>
                    <div class="saller_name">
                        <h4 class="pull-left padd-v-10 padd-h-10 full-width ">
                            @item.Firstname @item.Lastname
                        </h4>
                    </div>
                    <div class="edit-del padd-v-20 ">
                        <span>
                            <a href="javascript:void(0);" id="edit_one" onclick="EditBuyer(@item.BuyerId)">
                                <i class="material-icons colordarkGrey" >edit</i>
                            </a>
                        </span>
                        <span>
                            <a href="javascript:void(0);" onclick="EditBuyer(@item.BuyerId)">
                                <i class="material-icons colordarkGrey">delete</i>
                            </a>
                        </span>
                    </div>
                </div>

                <div class="col-md-12 col-xs-12  bdr-tp-1  padd-v-5">
                    @item.Phone
                </div>
                <div class="col-md-12 col-xs-12  padd-v-5">
                    @item.Email
                </div>
                <div class="col-md-12 col-xs-12  padd-v-5">
                    <p>@item.Note</p>
                </div>

                <div class="col-md-12 col-xs-12  padd-v-10">
                    <button class="btn ctaBtn btn_mainBlue save_btn">Buyer #@i</button>
                </div>

            </div></div>i++;
        }

        @*<div class="table-responsive">
                <table id="listingsellerTable" class="table table-bordered" style="width:100% !important">
                    <thead>
                        <tr class="btn_blue">
                            <th class="text-center">First Name</th>
                            <th class="text-center">Last Name</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Phone</th>
                            <th class="text-center">Address</th>
                            <th class="text-center">State</th>
                            <th class="text-center">City</th>
                            <th class="text-center">Postal Code</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                    {
                    <tr class="text-danger">
                        <td>@item.Firstname</td>
                        <td>@item.Lastname </td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Address</td>
                        <td>@item.State</td>
                        <td>@item.City</td>
                        <td>@item.PostalCode</td>
                        <td><a href="/Listing/EditSeller?SellerId=@item.SellerId">Edit</a><a href="/Listing/DeleteSeller?SellerId=@item.SellerId">Delete</a></td>
                    </tr>
                    }

                    </tbody>
                </table>
            </div>*@




        <script>
            $(document).ready(function () {

                $('#listingsellerTable').DataTable();

            });



        </script>

Offer/Offer/Views/Buyer/EditBuyer.cshtml
@model  DubTech.Framework.Ef.Buyer
@{
    Layout = null;
    }

@using (Html.BeginForm("EditBuyer", "Buyer", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
{  @Html.HiddenFor(m => m.BuyerId)
    @Html.HiddenFor(m => m.BuyerGroupId)
    <div class="col-sm-6 text-center col-xs-12 marg-t-15" id="edit_one">
        <div class="saller_img_edit">
            <img src="~/Content/images/demo/user.jpg" alt="">
            <button class="btn ctaBtn btn_mainBlue save_btn">
                <span for="dev">change</span>
                <input id="dev" type="file" />
            </button>
        </div>

        <div class="saller_name_edit padd-h-10 padd-v-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control required", placeholder = "First Name" })

                </div>
            </div>
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control required", placeholder = "Last Name" })
                </div>
            </div>
        </div>

        <div class="col-md-12 col-xs-12  bdr-tp-1 padd-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control required", placeholder = "Phone" })
                </div>
            </div>

            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control required", placeholder = "Email" })
                </div>
            </div>

        </div>
        <div class="col-md-12 col-xs-12  padd-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextAreaFor(m => m.Note, new { @class = "form-control", placeholder = "Buyer's Note", required = "required" })
                </div>
            </div>

        </div>
        <div class="col-md-12 col-xs-12  padd-v-10">

            <button type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn" id="submitseller">Save Changes</button>
            <button class="btn ctaBtn btn_mainBlue cancel_btn close_me" type="button" onclick="CancelEdit()" >Cancel</button>
            
        </div>
    </div>
}

Offer/Offer/Views/Buyer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<nav class="navbar subNavBar">
    <div class="container">
        <div id="sub_navigation">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/Buyer/NewBuyerGroup" class="btn btn_mainBlue navbar_btn btn_with_icon uppercase">
                        <i class="subnav_btn_icon material-icons">+</i>
                        Buyer Group
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group"><input type="text" class="form-control" placeholder="Search" id="txtsearch"></div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <select id="statusFilter" class="form-control">
                        <option value="All">Show All</option>
                        <option value="Active">Active</option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
</nav>


<section id="allListings" class="wrapEmAll">
    <div class="container" id="searchresult">

        @*Serach Result Partial Page*@
    </div>
</section>


@section scripts {
    
    <script>
    $(document).ready(function () {
        $.ajax({
            url: '/Buyer/_DispalyBuyerGroup', // The method name + paramater
            success: function (data) {
                $('#searchresult').html(data); // This should be an empty div where you can inject your new html (the partial view)
            }
        });
    });
    $('#txtsearch').change(function () {
        var Name = $('#txtsearch').val();
        var Status = $('#statusFilter').val();
        alert(Name);
        $.ajax({
            url: '/Buyer/_SearchResult?SearchType=' + Status + '&Name=' + Name,// The method name + paramater
            success: function (data) {
                $('#searchresult').html(data); // This should be an empty div where you can inject your new html (the partial view)

            }
        });
    });
    $('#statusFilter').change(function () {
        var Status = $('#statusFilter').val();
        alert(Status);
        $.ajax({
            url: '/Buyer/_SearchResult?SearchType=' + Status + '&Name=' + null, // The method name + paramater
            success: function (data) {
                $('#searchresult').html(data); // This should be an empty div where you can inject your new html (the partial view)

            }
        });
    });

    </script>
}

Offer/Offer/Views/Buyer/NewBuyer.cshtml
@model  Offer.Models.Buyer.NewBuyerModel
@{
    Layout = null;
    int BgId = Convert.ToInt32(TempData["BuyerGroupId"]);
}

<script>
    $(documemt).ready(function () {
        $('#BuyerGroupId').val(@BgId);
    });
</script>
@*<script>
        $('#submitseller').click(function ()
        {
            alert('hi');
            $.ajax({
                type: "POST",
                url: "Listing/NewSeller",
                data: $("FRM").serialize(),
                dataType:"json",
                success: function(resultData){
                    alert("Save Complete");
                    $('#sellistddiv').load('/Listing/SellersList?ListingID=' +  @ListId;
                }
            });
    </script>*@  


@using (Html.BeginForm("NewBuyer", "Buyer", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
{    @Html.HiddenFor(m => m.BuyerGroupId, new { id = "BuyerGroupId" })
    <div class="col-sm-6 text-center col-xs-12 marg-t-15">
        <div class="boxesPadding_full no-padd pull-left">
            <div class="saller_img_edit">
                <img src="~/Content/images/demo/user.jpg" id="sellerimg" />
                <button class="btn ctaBtn btn_mainBlue">
                    <span for="dev">Change </span>
                    <input type="file" style="width:100%; top:0px; height:100%; left:0px; position:absolute; z-index:10; opacity:0;" id="dev" />
                </button>

            </div>
            <div class="saller_name_edit padd-h-10 padd-v-10">
                <div class="form-group">
                    <div class="input-group half_padding">
                        @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control", placeholder = "First Name", required = "required" })

                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group half_padding">
                        @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control", placeholder = "Last Name", required = "required" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-xs-12  padd-10">

                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = "Phone", required = "required" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-xs-12  padd-10">
                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email", required = "required" })
                    </div>
                </div>

            </div>
            <div class="col-md-12 col-xs-12  padd-10">
                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextAreaFor(m => m.Note, new { @class = "form-control", placeholder = "Buyer's Note", required = "required" })
                    </div>
                </div>

            </div>

            <div class="col-md-12 col-xs-12  padd-v-10">

                <button type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn" id="submitseller">Save Changes</button>
                <button class="btn ctaBtn btn_mainBlue cancel_btn close_me" onclick="cancelNewBuyer()">Cancel</button>

                
            </div>
        </div>
    </div>
}

Offer/Offer/Views/Buyer/_EditBuyerGroup.cshtml
@model Offer.Models.Buyer.BuyerGroupItem

@using (Html.BeginForm("EditBuyerGroup", "Buyer", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
{    @Html.HiddenFor(m => m.BuyerGroupId)

    <div class=" col-lg-12 listingBox status_active padd-10 ">
        <div class="col-md-12 col-xs-12 text-center ">
            <select name="color-scheme" class="form-control drpstatus">

                <option selected value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="Escrow">Escrow</option>
                <option value="Closed">Closed</option>
            </select>
            
        </div>

        

        <div class="col-md-12 col-xs-12 entry text-center">
            <p class="colordarkGrey">Search Areas</p>
            @Html.TextAreaFor(m => m.SearchAreas, new { @class = "form-control", placeholder = "Search Areas", required = "required" })
        </div>
        <div class="col-md-12 col-xs-12 text-center heading_status">
            <p class="colordarkGrey ">Listing Agent</p>
            <h4><strong>@Model.AgentFirstname  @Model.AgentLastname</strong></h4>
            <p class="colordarkGrey ">test</p>
            <p class="colordarkGrey ">@Model.AgentPhone</p>
            <p>@Model.AgentEmail</p>
        </div>
        <div class="col-md-12 col-xs-12  text-center">
            <span class="pull-left text-center">

                <span class="topic_has_icon">
                    Email Notification <br> <select name="color-scheme" class="form-control drpstatus">

                        <option selected value="Yes">Immediately</option>
                        <option value="No">Delayed</option>

                    </select>
                </span>
            </span>
            <span class="pull-right text-center">

                <span class="topic_has_icon">
                    Text Notification <br>
                    <input type="checkbox" disabled="">
                </span>
            </span>
        </div>
        <div class="col-md-12 col-xs-12  entry">
            <span class="pull-left text-center">
                Creation Date <br> <strong>@String.Format("{0:dd MMM. yyyy}", Model.DateCreated)</strong>
            </span>
            <span class="pull-right text-center">
                <button class="btn ctaBtn btn_mainBlue save_btn col-xs-12 no-padd txt-upper " type="submit"> Edit  </button>
            </span>
        </div>

        <div class="col-md-12 col-xs-12">
            @*<p class="colorGrey">Offer Instructions</p>*@
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextAreaFor(m => m.BuyerNote, new { @class = "form-control", placeholder = "Buyer Note", required = "required" })
                </div>
            </div>
        </div>
    </div>

}