Offer/Offer/Models/Offer/NewInquiryModel.cs
using Offer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Offer
{
    public class NewInquiryModel : Inquiry
    {
        public bool Lender { get; set; }
        public bool PreApproval { get; set; }
        public bool SellerBuyHome { get; set; }
        public bool Interior { get; set; }
        public bool Schedule { get; set; }

    }
}

Offer/Offer/Models/Offer/NewOfferGroupModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Offer.Models.Offer
{
    public class NewOfferGroupModel : NewOfferModel
    {
        [Required(ErrorMessage = "Please Enter Buyer First Name")]
        [Display(Name = "First Name")]
        public string BuyerFirstname { get; set; }
        [Required(ErrorMessage = "Please Enter Buyer Last Name")]
        [Display(Name = "First Name")]
        public string BuyerLastname { get; set; }
        [Required(ErrorMessage = "Please Enter Agent First Name")]
        [Display(Name = "First Name")]
        public string AgentFirstname { get; set; }
        [Required(ErrorMessage = "Please Enter Buyer Last Name")]
        [Display(Name = "First Name")]
        public string AgentLastname { get; set; }
        public string Brokrage { get; set; }
        public string AgentPhoneNo { get; set; }
        public Nullable<int> ListingId { get; set; }
        public Nullable<int> BuyerGroupId { get; set; }
        public string OfferType { get; set; }
        public Guid ListingUniqueId { get; set; }
    }
}

Offer/Offer/Models/Offer/NewOfferModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Offer.Models.Offer
{
    public class NewOfferModel 
    {
        public DateTime? OfferDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        [Required(ErrorMessage = "Please Enter Offer Amount")]
        [Display(Name = "OfferAmount")]
        [RegularExpression(@"^[+-]?\$?([0-9]+(,[0-9]{3})*)?(\.([0-9]+)?)?$",
        ErrorMessage = "Please Enter Proper Amount.")]
        public int? OfferAmount { get; set; }
        public string LoanType { get; set; }
        public DateTime? ClosingDate { get; set; }
        [Required(ErrorMessage = "Please Enter Deposit Amount")]
        [Display(Name = "DepositAmount")]
        [RegularExpression(@"^[+-]?\$?([0-9]+(,[0-9]{3})*)?(\.([0-9]+)?)?$",
        ErrorMessage = "Please Enter Proper Amount.")]
        public decimal DepositAmount { get; set; }
        public string Status { get; set; }
        [Required(ErrorMessage = "Please Enter Loan Amount")]
        [Display(Name = "LoanAmount")]
        [RegularExpression(@"^[+-]?\$?([0-9]+(,[0-9]{3})*)?(\.([0-9]+)?)?$",
        ErrorMessage = "Please Enter Proper Amount.")]
        public decimal LoanAmount { get; set; }
        public string AgentEmail { get; set; }
        [Required(ErrorMessage = "Please Enter Buyer's Closing Cost")]
        [Display(Name = "BuyersClosingCost")]
        [RegularExpression(@"^[+-]?\$?([0-9]+(,[0-9]{3})*)?(\.([0-9]+)?)?$",
        ErrorMessage = "Please Enter Proper Amount.")]
        public decimal BuyersClosingCost { get; set; }
          [Required(ErrorMessage = "Please Enter Close of Escrow")]
        [Display(Name = "CloseofEscrow")]
        [RegularExpression(@"^\$?[0-9]{1,3}(?:\.[0-9]{2})?$",
        ErrorMessage = "Please Enter Proper Days.")]
        public int CloseofEscrow { get; set; }
        public int OfferGroupId { get; set; }
        public bool Contingent { get; set; }
        public string Comments { get; set; }
       

    }
}

Offer/Offer/Models/Offer/OfferGroupSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Offer
{
    public class OfferGroupSearchModel
    {
        public OfferGroupSearchModel()
        {
            OfferGroupItems = new List<OfferGroupGridItem>();
        }

        public List<OfferGroupGridItem> OfferGroupItems { get; set; }
    }

    public class OfferGroupGridItem
    {
        public int OfferGroupId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string MlsNumber { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public string Status { get; set; }
        public Nullable<int> ListAmount { get; set; }
        public string BuyerFirstname { get; set; }
        public string BuyerLastname { get; set; }
        public string AgentFirstname { get; set; }
        public string AgentLastname { get; set; }
        public string AgentEmail { get; set; }
        public string AgentPhone { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<decimal> OfferAmount { get; set; }
        public string LoanType { get; set; }
        public string InternalNote { get; set; }

        public Nullable<System.DateTime> CounterOfferDate { get; set; }
        public Nullable<decimal> CounterOfferAmount { get; set; }
        public string CounterLoanType { get; set; }
        public string CounterInternalNote { get; set; }

        public int? OfferId { get; set; }

        public int? CounterOfferId { get; set; }
    }

    public class OfferSearchModel
    {
        public OfferSearchModel()
        {
            OfferItems = new List<OfferGridItem>();
        }
        public List<OfferGridItem> OfferItems { get; set; }
    }

    public class OfferGridItem
    { 
        //New Fields
        public int? OfferId { get; set; }
        public int BuyerCounter { get; set; }
        public Nullable<System.DateTime> OfferExpiryDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Deposite { get; set; }
        public Nullable<decimal> ClosingCost { get; set; }
        public string Contingent { get; set; }
        public string Financing { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public int CloseofEscrow { get; set; }
        public string BuyersAgent { get; set; }
        public string loanstatus { get; set; }
        public string offerstatus { get; set; }
        public string Note { get; set; }

    }
}

Offer/Offer/Models/SubmissionHub/ListingDetailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.SubmissionHub
{
    public class ListingDetailView
    {
        public string Address { get; set; }

        public string ListAmount { get; set; }

        public string ListDate { get; set; }
        public string ExpiryDate { get; set; }

        public string Instructions { get; set; }

        public string ListAgentName { get; set; }

        public string ListAgentEmail { get; set; }

        public string ListAgentCompany { get; set; }

        public string ListAgentPhone { get; set; }

        public string PropertyDetailsUrl { get; set; }

        public int ListingId { get; set; }

        public string ListingStatus { get; set; }

        public bool? IsAgentOffer { get; set; }

        public string ListingUniqueId { get; set; }

    }
}

Offer/Offer/Controllers/SubmissionHubController.cs
using Offer;
using Offer.Api;
using Offer.Data;
using Offer.Models.Offer;
using Offer.Models.Settings;
using Offer.Models.SubmissionHub;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace OfferManagement.Mvc.Controllers
{
    [AllowAnonymous]
    public class SubmissionHubController : Controller
    {

        OfferApiController Api = new OfferApiController();
        AttachmentService atchsrvc = new AttachmentService();
        // GET: Settings
        public ActionResult ListingDetail(string Id, bool? agentOffer = null)
        {

            ViewBag.StatusResult = Api.GetListingStatus();
            //todo: load Listing from database by id
            Listing listing = Api.GetListingByUniqueId(Id);
            ListingDetailView model = new ListingDetailView();
            model.ListingId = listing.ListingId;
            model.Address = FormatHelper.FormatAddressCityStateZip(listing.Address, listing.City, listing.State, listing.PostalCode, false);
            model.Instructions = listing.OfferInstructions;
          
            User agent = Api.GetUserDetail(Convert.ToInt32(listing.CreatedByUserId));
            model.ListAgentCompany = agent.CompanyName;
            model.ListAgentEmail = agent.Email;
            model.ListAgentName = FormatHelper.FormatFullName(agent.Firstname, agent.Lastname);
            model.ListAgentPhone = FormatHelper.FormatPhoneForDisplay(agent.PhoneNumber);
            model.ListAmount = listing.ListAmount != null ? String.Format("{0:C}", (int)listing.ListAmount) : "";
            model.ListDate = String.Format("{0:MM/dd/yyyy}", listing.ListDate);
            model.ExpiryDate = String.Format("{0:MM/dd/yyyy}", listing.ListingExpirationDate);
            model.ListingStatus = listing.Status_LookupCode;
            model.PropertyDetailsUrl = listing.DetailUrl;
            model.ListingUniqueId = listing.UniqueId;

            return View("ListingDetail", model);
        }

        public ActionResult AgentOffer(string id)
        {
            return ListingDetail(id);
        }

        public PartialViewResult _AgentSubmissionConfirmation(int OfferGroupId)
        {
           
           OfferGroup offerGroups = Api.GetOfferGroupDetail(OfferGroupId);
          
           return PartialView(offerGroups);
        }
        public PartialViewResult _AgentSubmitOffer()
        {
            return PartialView();
        }
     
        [HttpGet]
        public PartialViewResult AgentOfferForm(int ListingId, string OfferType)
        {


           
            ViewBag.financing = Api.GetLoanTypeStatus();
            NewOfferGroupModel model = new NewOfferGroupModel();
            if (OfferType == "ListingOfferGroup")
            {
                model.ListingId = ListingId;
                model.BuyerGroupId = null;
                model.OfferType = "ListingOfferGroup";
            }
            if (OfferType == "BuyerOfferGroup")
            {
                model.BuyerGroupId = ListingId;
                model.ListingId = null;
                model.OfferType = "BuyerOfferGroup";
            }

            return PartialView();
        }
        [HttpPost]
        public void AgentOfferForm(NewOfferGroupModel model, List<HttpPostedFileBase> offerfiles)
        {
            OfferGroup offerGroup = new OfferGroup();
            //Distinguish Agent and Buyer Offer
            if (model.OfferType == "ListingOfferGroup")
            {
                offerGroup.ListingId = model.ListingId;
                offerGroup.BuyerGroupId = null;
                offerGroup.OfferGroupType = "ListingOfferGroup";

            }
            if (model.OfferType == "BuyerOfferGroup")
            {
                offerGroup.BuyerGroupId = model.BuyerGroupId;
                offerGroup.ListingId = null;
                offerGroup.OfferGroupType = "BuyerOfferGroup";
            }

            offerGroup.AgentEmail = model.AgentEmail;
            offerGroup.AgentFirstname = model.AgentFirstname;
            offerGroup.AgentLastname = model.AgentLastname;
            offerGroup.AgentPhone = model.AgentPhoneNo;
            offerGroup.BuyerFirstname = model.BuyerFirstname;
            offerGroup.BuyerLastname = model.BuyerLastname;
            
            offerGroup.UniqueId = Guid.NewGuid();

            Offer.Data.Offer offer = new Offer.Data.Offer();
            offer.BuyerClosingCosts = model.BuyersClosingCost;
            offer.ClosingDate = Convert.ToDateTime(model.ClosingDate);
            offer.Comments = model.Comments;
            offer.EarnestDeposit = model.DepositAmount;
            offer.ExpirationDate = model.ExpirationDate ?? DateTime.Now;
            offer.IsBuyerSubmitted = true; // New Offer Group always assumes first offer is from buyer
            offer.LoanAmount = model.LoanAmount;
            offer.OfferAmount = model.OfferAmount ?? 0; //todo: offer amount required
            offer.OfferDate = model.OfferDate ?? DateTime.Now;
            offer.CloseofEscrow = model.CloseofEscrow;
            offer.LoanType_LookupCode = model.LoanType;
            offer.OfferStatus_LookupCode = "new";
            offer.Contingent = model.Contingent;
            offer.CreatedByUserId = null;
            offer.ModifiedByUserId = null;
            // Save Offer Group

            Api.OfferGroupSave(offerGroup);
            //Save Offer
            offer.OfferGroupId = offerGroup.OfferGroupId;
            
            Api.SaveOffer(offer);
            if (offerfiles != null)
            {
                foreach (var item in offerfiles)
                {

                    if (item != null && item.ContentLength > 0)
                    {
                        string url = string.Empty;
                        string fileName = Guid.NewGuid().ToString();
                        string path = string.Empty;
                        path = Path.Combine(Server.MapPath("~/Img"), fileName.ToString() + "." + Path.GetExtension(item.FileName).Substring(1));
                        item.SaveAs(path);
                        url = fileName + "." + Path.GetExtension(item.FileName).Substring(1);
                    }
                }
            }

            string body = string.Empty;
            using (StreamReader reader = new StreamReader(Server.MapPath("~/EmailTemplate/OfferLink.html")))
            {
                body = reader.ReadToEnd();
            }
            string offerurl = null;
            offerurl=String.Format("{0}{1}{2}", RootUrl, "/SubmissionHub/ViewOffer?OfferUniqueNo=", offerGroup.UniqueId);
            body = body.Replace("{offerurl}", offerurl);
            Api.SendEmail("Offer Link", body, offerGroup.AgentEmail);

            
           
        }
        public static string RootUrl
        {
            get
            {
                return ConfigurationManager.AppSettings["RootUrl"].TrimEnd('/');
            }
        }
      



        public ActionResult AgentSubmissionConfirmation()
        {
            return View();
        }

        public ActionResult ViewOffer(Guid OfferUniqueNo)
        {  

            OfferGroupSearchModel offerGroupSearchModel = new OfferGroupSearchModel();
            List<OfferGroupSummary> offerGroups = Api.GetOfferGroupByUniqueId(OfferUniqueNo);
            OfferSearchModel offerSearchModel = new OfferSearchModel();
            foreach (OfferGroupSummary offerGroup in offerGroups)
            {
                offerGroupSearchModel.OfferGroupItems.Add(new OfferGroupGridItem()
                {
                    OfferGroupId = offerGroup.OfferGroupId,
                    AgentEmail = offerGroup.AgentEmail,
                    AgentFirstname = offerGroup.AgentFirstname,
                    AgentLastname = offerGroup.AgentLastname,
                    BuyerFirstname = offerGroup.BuyerFirstname,
                    BuyerLastname = offerGroup.BuyerLastname,
                    InternalNote = offerGroup.InternalNote,
                    //LoanType = offerGroup.LoanType != null ? offerGroup.LoanType.Value : "",
                    OfferAmount = offerGroup.OfferAmount,
                    OfferDate = offerGroup.OfferDate,
                    CounterInternalNote = offerGroup.CounterInternalNote,
                    //CounterLoanType = offerGroup.CounterLoanType != null ? offerGroup.CounterLoanType.Value : "",
                    CounterOfferAmount = offerGroup.CounterOfferAmount,
                    CounterOfferDate = offerGroup.CounterOfferDate,
                    CounterOfferId = offerGroup.CounterOfferId,
                    OfferId = offerGroup.OfferId,


                });
                List<Offer.Data.Offer> offers = Api.GetOfferByGroup(offerGroup.OfferGroupId);
                foreach (Offer.Data.Offer off in offers)
                {
                    offerSearchModel.OfferItems.Add(new OfferGridItem()
                    {
                        OfferId = off.OfferId,
                        CloseofEscrow = Convert.ToInt32(off.CloseofEscrow),
                        OfferExpiryDate = off.ExpirationDate,
                        PurchasePrice = off.OfferAmount,
                        Deposite = off.EarnestDeposit,
                        ClosingCost = off.BuyerClosingCosts,
                        Contingent = off.Contingent != true ? "No" : "Yes",
                        Financing = off.LoanType_LookupCode,
                        LoanAmount = off.LoanAmount,
                        BuyersAgent = offerGroup.AgentFirstname + " " + offerGroup.AgentLastname,
                        loanstatus = offerGroup.LoanType_LookupCode,
                        offerstatus = off.OfferStatus_LookupCode,
                        Note = off.Comments
                    });
                }
              

            }
            return View(offerSearchModel.OfferItems);
        }
        private class UploadedFileResult
        {

Offer/Offer/Views/SubmissionHub/AgentOfferForm.cshtml
@model Offer.Models.Offer.NewOfferGroupModel

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/Views/Offer/NewOfferGroup.js"></script>
@using (Html.BeginForm("AgentOfferForm", "SubmissionHub", FormMethod.Post, new { id = "newOfferGroupForm", enctype = "multipart/form-data" }))
{
     @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.ListingId)
    @Html.HiddenFor(m => m.BuyerGroupId)
    @Html.HiddenFor(m => m.OfferType)
<div class="col-sm-6">
    <div class="boxesPadding_full boxesPadding pull-left">
        <h4 class="boxesTopic entry padd-10 ">
            <i class="material-icons icon_has_topic">account_circle</i>
            <span class="topic_has_icon">Buyers</span>
        </h4>

        <br>
        <div id="buygrpdiv"></div>
        <div id="buyerdiv"></div>
        @*@if (Model.BuyerFirstname == null || Model.BuyerLastname == null)
        {
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.BuyerFirstname, new { @class = "form-control", placeholder = "Buyer First Name"})
                    @Html.ValidationMessageFor(m => m.BuyerFirstname)

                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.BuyerLastname, new { @class = "form-control", placeholder = "Buyer Last Name" })
                    @Html.ValidationMessageFor(m => m.BuyerLastname)
                </div>
            </div>
        </div>

        }
        else
        {*@
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.BuyerFirstname, new { @class = "form-control", placeholder = "Buyer First Name"})
                    @Html.ValidationMessageFor(m => m.BuyerFirstname)
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.BuyerLastname, new { @class = "form-control", placeholder = "Buyer Last Name" })
                    @Html.ValidationMessageFor(m => m.BuyerLastname)
                </div>
            </div>
        </div>

        @*}*@



    </div>

    <div class="boxesPadding_full boxesPadding pull-left marg-v-10">
        <h4 class="boxesTopic entry padd-10 ">
            <i class="material-icons icon_has_topic">account_circle</i>
            <span class="topic_has_icon">Buyer's Agent</span>
        </h4>

        <br>
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.AgentFirstname, new { @class = "form-control", placeholder = "Agent First Name"})
                    @Html.ValidationMessageFor(m => m.AgentFirstname)
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.AgentLastname, new { @class = "form-control", placeholder = "Agent Last Name" })
                    @Html.ValidationMessageFor(m => m.AgentLastname)
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Brokrage, new { @class = "form-control", placeholder = "Agent Brokrage" })
                  
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group">
                <div class="input-group full_width">
                    <input type="text" class="form-control" placeholder="Address"  maxlength="100">
                 
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">

                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.AgentEmail, new { @class = "form-control", placeholder = "Agent Email" })
                    @Html.ValidationMessageFor(m => m.AgentEmail)
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.AgentPhoneNo, new { @class = "form-control", placeholder = "Agent PhoneNo" })
                    @Html.ValidationMessageFor(m => m.AgentPhoneNo)
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group">
                <div class="input-group full_width">
                    <textarea rows="4" class="full-width text-justify padd-5" style="width:100%; resize:none;" disabled>Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type and scrambled it to make a type specimen book. </textarea>
                </div>
            </div>
        </div>


    </div>
</div>

<div class="col-sm-6">
    <div class="boxesPadding_full boxesPadding pull-left">
        <h4 class="boxesTopic entry padd-10 ">
            <i class="material-icons icon_has_topic">account_circle</i>
            <span class="topic_has_icon">Offer Details</span>
        </h4>

        <br>
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">


                    @Html.TextBoxFor(m => m.OfferAmount, new { @class = "form-control", placeholder = "Purchase Price" })
                    @Html.ValidationMessageFor(m => m.OfferAmount)
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">


                    @Html.TextBoxFor(m => m.DepositAmount, new { @class = "form-control", placeholder = "Deposit Amount" })
                    @Html.ValidationMessageFor(m => m.DepositAmount)
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">

                    @Html.TextBoxFor(m => m.LoanAmount, new { @class = "form-control", placeholder = "Loan Amount"})
                    @Html.ValidationMessageFor(m => m.LoanAmount)
                </div>
            </div>
        </div>


        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">

                    @Html.DropDownListFor(model => model.LoanType, new SelectList(ViewBag.financing, "Code", "DisplayName"), "Choose an Option", new { @class = "form-control", id = "drpfinncing" })
                    @Html.ValidationMessageFor(m => m.LoanType)
                    @*<select id="statusFilter" class="form-control" required name="LoanType">
                        <option value="">Choose an option</option>
                        <option value="Cash">Cash</option>
                        <option value="Conventional">Conventional</option>
                        <option value="FHA">FHA</option>
                        <option value="VA">VA</option>
                        <option value="Other">Other</option>
                    </select>*@

                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.BuyersClosingCost, new { @class = "form-control", placeholder = "Buyer Closing Cost Credits" })
                    @Html.ValidationMessageFor(m => m.BuyersClosingCost)
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group">
                    @Html.TextBoxFor(m => m.CloseofEscrow, new { @class = "form-control", style = "width:60px", placeholder = "Days", maxlength = "10" })
                    @Html.ValidationMessageFor(m => m.CloseofEscrow)
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group move_down_group full_width">
                <div class="input-group">
                    @Html.CheckBoxFor(m => m.Contingent, new { @class = "", @checked="checked", id = "sameListing2" })

                    <label for="sameListing2" class="">Is the offer contingent on the buyers sale?</label>

                </div>
            </div>
        </div>





        <div class="col-sm-12 marg-t-15">
            <div class="form-group">
                <label>Offer Expiration Date </label>
                <div class="input-group date full_width">
                    @Html.TextBoxFor(m => m.ClosingDate, new { @class = "form-control", placeholder = "Closing Date", required = "required", id = "listing_date" }) <span class="input-group-addon"><i class="material-icons">today</i></span>
                </div>


            </div>
        </div>

        <div class="col-md-12  col-xs-12">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextAreaFor(m => m.Comments, new { @class = "form-control", rows = "4", placeholder = "Comments to listing agent about your offer", id = "txtcomment", style = "resize:none" })

                </div>
            </div>
            <div class="form-group">
                <div class="input-group full_width" style="position:relative">
                    <textarea class="form-control" style="resize:none" placeholder="Drop offer, pre-approval and proof of fund to close here (or click to upload)" rows="4"></textarea>
                    <input type="file" name="offerfiles" multiple style="width:100%; top:0px; height:100%; left:0px; position:absolute; z-index:10; opacity:0;" id="fileupload">
                    <br /><br />
                    <!-- The global progress bar -->
                    <div id="progress" class="progress">
                        <div class="progress-bar progress-bar-success"></div>
                    </div>
                    <!-- The container for the uploaded files -->
                    <div id="files" class="files"></div>
                    <br>

                    <p />
                </div>
            </div>
        </div>



    </div>


</div>
<div class="col-md-12 col-xs-12  padd-v-10">

    
    <button id="newOfferGroupSubmitButton" type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn">Submit</button>

</div>
                  }

<div class="col-xs-12 marg-v-10">
    <div class="bg-warning padd-10">
        <h4>How EVERY OFFER works for agents not on EVERY OFFER:</h4>
        <ol>

            <li>Every offer submitted through Every Offer is automatically emailed to the sellers agent.</li>
            <li>To accurate track all of your buyer offers, upload sellers counter offers into Every Offer.</li>
            <li>Use Every Offer to continue to submit counter offers and track every offer.</li>
        </ol>
    </div>
</div>
<script src="~/javascripts/bootstrap-datepicker.min.js"></script>
<script>
    $(document).ready(function () {
        $("#listing_date, #status_change_date, #card_expire_date").datepicker({
            todayHighlight: true,

        });
    });

    function submitNewOfferGroup() {
        var url = "/SubmissionHub/AgentOfferForm"; // the script where you handle the form input.

        $.ajax({
            type: "POST",
            url: url,
            data: $("#newOfferGroupForm").serialize(), // serializes the form's elements.
            success: function (result) {
                $.ajax({
                    type: "post",
                    url: "/SubmissionHub/_AgentSubmissionConfirmation?OfferGroupId=" + result.OfferGroupId,

                    success: function (msg) {
                        alert("Offer is submitted.");
                        $('#confirmoffer').html(msg);
                        $('#NewOfferGroup').hide();
                        $('#confirmoffer').show();
                    }
                });
                
            }
        });
    }

</script>

Offer/Offer/Views/SubmissionHub/AgentSubmissionConfirmation.cshtml
@{
    ViewBag.Title = "AgentSubmissionConfirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgentSubmissionConfirmation</h2>

Offer/Offer/Views/SubmissionHub/_AgentSubmissionConfirmation.cshtml
@model Offer.Models.Offer

<section class="marg-b-20">

    <div class="col-md-12 col-xs-12">
        <span class="topic_has_icon">
            Thank you, your offer has been submitted.
            <br />
            <br />
            You may review your offer at anytime by
            visiting the following URL:
            <br />
            <br />
            <a href="http://localhost:58715/SubmissionHub/ViewOffer?OfferUniqueNo=@Model.UniqueId">
                Click Here to continue (take offer to ViewOffer page)
            </a>

        </span>
    </div>
</section>