Offer/Offer/Models/Register/BillingView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Offer.Models.Register
{
    public class BillingView
    {
        public string CreditCardNumber { get; set; }

        public int ExpirationMonth { get; set; }
        
        public int ExpirationYear { get; set; }

        public string NameOnCard { get; set; }

        public string CardType { get; set; }

        public Guid RegistrationCode { get; set; }
    }
}

Offer/Offer/Models/Settings/AttachmentService.cs
using Offer.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Offer.Models.Settings
{
    public  class AttachmentService
    {
       

      
        #region Temporary Files

        /// <summary>
        /// Saves file to temporary storage
        /// </summary>
        /// <returns>The filename (guid) of the temporary file created</returns>
        public  string SaveTemporaryFile(byte[] file)
        {
            string filename = Guid.NewGuid().ToString();
            string tempFilePath = Path.Combine(Config.TemporaryFilePath, filename);
            File.WriteAllBytes(tempFilePath, file);
            return filename;
        }

        /// <summary>
        /// Saves file to temporary storage
        /// </summary>
        /// <returns>The filename (guid) of the temporary file created</returns>
        public  string SaveTemporaryFile(Stream stream)
        {
            stream.Position = 0;
            string filename = Guid.NewGuid().ToString();
            string tempFilePath = Path.Combine(Config.TemporaryFilePath, filename);
            using (FileStream fs = File.Create(tempFilePath))
            {
                stream.CopyTo(fs);
            }

            return filename;
        }


        /// <summary>
        /// Load temporary file
        /// </summary>
        public  byte[] GetTemporaryFile(string filename)
        {
            string tempFilePath = Path.Combine(Config.TemporaryFilePath, filename);
            return File.ReadAllBytes(tempFilePath);
        }

        #endregion


        #region Path Resolution Helpers

        /// <summary>
        /// Get calculated path location: [root]\ (attachmentId divided by 100000), eg attachmentid 120000 goes to [root]\12
        /// </summary>
        public static string GetAttachmentFullPath(Attachment attachment, bool createDirectoryIfMissing, string attachmentRootPath)
        {
            try
            {
                int destinationNumber = (int)Math.Floor((double)attachment.AttachmentId / 100000);
                string path = Path.Combine(attachmentRootPath, destinationNumber.ToString());

                //verify path exists and create if needed
                if (createDirectoryIfMissing)
                    if (!Directory.Exists(path)) Directory.CreateDirectory(path);

                return Path.Combine(path, attachment.LocalFilename);
            }
            catch (Exception ex)
            {
                throw new Exception("Failed to determine attachment path for attachment id: " + attachment.AttachmentId.ToString(), ex);
            }
        }

        public static string GetAttachmentFullPath(Attachment attachment, bool createDirectoryIfMissing)
        {
            return GetAttachmentFullPath(attachment, createDirectoryIfMissing, Config.AttachmentRootPath);
        }

        #endregion
    }
}

Offer/Offer/Models/Settings/Config.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace Offer.Models.Settings
{
    
         public  class Config
    {
        public static string ApplicationName
        {
            get
            {
                return ConfigurationManager.AppSettings["ApplicationName"];
            }
        }

        public static string TemporaryFilePath
        {
            get
            {
                return ConfigurationManager.AppSettings["TemporaryFilePath"];
            }
        }

        public static string AttachmentRootPath
        {
            get
            {
                return ConfigurationManager.AppSettings["AttachmentRootPath"];
            }
        }

    
}
     
}

Offer/Offer/Controllers/ProfileController.cs
using DubTech.Framework.Ef;
using Offer.Models.Account;
using OfferManagement.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using DubTech.Infrastructure.Web;

namespace OfferManagement.Mvc.Controllers
{
    public class ProfileController : DubController
    {
        public ProfileController()
        {
            this.userService = new UserService(CurrentUser);

        }

        private UserService userService { get; set; }
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MyProfile()
        {
            User user = userService.GetUserDetail(1);
            ProfileData model = new ProfileData();
            model.UserId = user.UserId;
            model.Firstname = user.Firstname;
            model.Lastname = user.Lastname;
            model.Email = user.Email;
            model.PhoneNumber = user.PhoneNumber;
            model.CompanyName = user.CompanyName;
            model.LicenseNumber = user.LicenseNumber;
            model.Enabled = user.Enabled;
            model.Password = user.Password;
            return View(model);
        }
        //public ActionResult EditProfile()
        //{
        //    User user = UserService.GetUserDetail(1);
        //    ProfileData model = new ProfileData();
        //    model.UserId = user.UserId;
        //    model.Firstname = user.Firstname;
        //    model.Lastname = user.Lastname;
        //    model.Email = user.Email;
        //    model.PhoneNumber = user.PhoneNumber;
        //    model.CompanyName = user.CompanyName;
        //    model.LicenseNumber = user.LicenseNumber;
        //    model.Enabled = user.Enabled;
        //    //return View(user);
        //    return View(model);
        //}
        [HttpPost]
        public ActionResult EditProfile(User model, HttpPostedFileBase UserImg)
        {
            if (UserImg != null && UserImg.ContentLength > 0)
            {
                string url = string.Empty;
                string fileName = Guid.NewGuid().ToString();
                string path = string.Empty;
                path = Path.Combine(Server.MapPath("~/Img"), fileName.ToString() + "." + Path.GetExtension(UserImg.FileName).Substring(1));
                UserImg.SaveAs(path);
                url = fileName + "." + Path.GetExtension(UserImg.FileName).Substring(1);
                //model.TableFieldUsedForImage = url;
            }
            else
            {
                User user = userService.GetUserDetail(1);
                //model.TableFieldUsedForImage = user.TableFieldUsedForImage;
            }
            userService.EditUser(model);
            return RedirectToAction("MyProfile");
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                User user = userService.GetUserDetail(1);
                if (user != null)
                {
                    if (model.OldPassword == user.Password)
                    {
                        user.Password = model.NewPassword;
                        userService.ChangePassword(user.UserId, user.Password);
                        Session.Clear();
                        Session.Abandon();
                        return RedirectToAction("MyProfile");
                    }
                    else
                    {
                        Response.Write(@"<script language='javascript'>alert('Password is Incorrect.');</script>");
                        return View();
                    }
                }
                else
                {
                    Response.Write(@"<script language='javascript'>alert('User not Exists.');</script>");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

Offer/Offer/Controllers/SettingsController.cs
using Offer.Api;
using Offer.Models.Account;
using System;
using System.Web.Mvc;

namespace OfferManagement.Mvc.Controllers
{
    public class SettingsController : Controller
    {
        OfferApiController api = new OfferApiController();
        // GET: Settings
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult _Billing()
        {
            return PartialView();
        }
        public PartialViewResult _ListingDefaults()
        {
            return PartialView();
        }
        public PartialViewResult _ManageUsers()
        {
            return PartialView();
        }
        public PartialViewResult _Profile()
        {
           
            var user = api.GetUserDetail(Convert.ToInt32(Session["UserId"]));
            ProfileData pfdata = new ProfileData();
            pfdata.Firstname = user.Firstname;
            pfdata.Lastname = user.Lastname;
            pfdata.Email = user.Email;
            pfdata.PhoneNumber = user.PhoneNumber;

            return PartialView(pfdata);
        }
        public PartialViewResult ChangePassword()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
               
                var user = api.GetUserDetail(Convert.ToInt32(Session["UserId"]));
                if (user.Password == model.OldPassword)
                {
                    api.ChangePassword(Convert.ToInt32(Session["UserId"]), model.NewPassword);
                    return Json((new { Success = "True", Message = "Password changed sucessfully." }), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json((new { Success = "false", Message = "Please fill required feilds." }), JsonRequestBehavior.AllowGet);

                }


            }
            else
            {
                return View();
            }


        }

    }
}

Offer/Offer/Views/Settings/ChangePassword.cshtml
@model Offer.Models.Account.ChangePasswordModel

<div class="boxesPadding">
    <h4 class="boxesTopic">
       
        <span class="topic_has_icon">Change Password</span>
    </h4>
    <hr>
    <div class="row boxesParagraph">
        @using (Html.BeginForm("ChangePassword", "Settings", FormMethod.Post, new { id = "FRM8", enctype = "multipart/form-data", @class = "form-horizontal" }))
        {



            @Html.ValidationSummary(true)
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Old Password</label>
                <div class="col-sm-9">
                    @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control", placeholder = "Old Password" })

                    @Html.ValidationMessageFor(m => m.OldPassword)
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> New Password</label>
                <div class="col-sm-9">
                    @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control", placeholder = "New Password", id = "password" })
                    <span id="result"></span>
                    @Html.ValidationMessageFor(m => m.NewPassword)
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Confirm New Password</label>
                <div class="col-sm-9">
                    @Html.PasswordFor(m => m.ConfirmNewPassword, new { @class = "form-control", placeholder = "Re-Type New Password" })

                    @Html.ValidationMessageFor(m => m.ConfirmNewPassword)
                </div>
            </div>






    <div class="row-fluid call_to_action">
        <button type="button" class="btn btn-secondary" onclick="CancelChangePass()">Close</button>
        <button type="submit" class="btn btn-primary" id="savepass">Save changes</button>
    </div>
        }
    </div>
</div>
@*<script>
    
        $('#savepass').click(function () {
            alert('hi');
          //  var formData = new FormData($('#FRM8')[0]);
            $.ajax({
                url: '../Settings/ChangePassword',
                type: 'POST',
                data: $('form').serialize(),
                sucess: function (data) {
                    if (data.Success == true)
                    {
                        alert(data.Message);
                        window.location.href = "http://www.google.com";
                    }
                    else {
                        alert(data.Message);
                        window.location.reload();
                    }
                    
                },
                error: function () { alert('An error occured.'); }
            });
        });
   
</script>*@

Offer/Offer/Views/Settings/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav class="navbar subNavBar">
    <div class="container">
        <div id="sub_navigation">
            <ul class="nav navbar-nav">
                <li class="active">
                    <ul class="you_are_here">
                        <li class="hidden-xs go_back_home"><a href="index.html">Home</a></li>
                        <li class="hidden-xs"><i class="material-icons">navigate_next</i></li>
                        <li class="current_page"><a class="active" href="#">Settings</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<section id="addNewListing" class="wrapEmAll padd-v-15">
    <div class="container">
        <div class="col-md-3 ">
            <div class="col-md-12 boxesPadding_full no-padd">
                <ul class="nav nav-tabs vertival-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#user_info" aria-controls="user_info" role="tab" data-toggle="tab">Profile</a></li>
                    <li role="presentation"><a href="#manage_users" aria-controls="manage_users" role="tab" data-toggle="tab">Manage Users</a></li>
                    <li role="presentation"><a href="#billing" aria-controls="billing" role="tab" data-toggle="tab">Billing</a></li>
                    <li role="presentation"><a href="#listing_default" aria-controls="listing_default" role="tab" data-toggle="tab">Listing Defaults</a></li>
                </ul>

            </div>
        </div>
        <div class="tab-content col-md-9 no-padd">
            <div role="tabpanel" class="tab-pane active" id="user_info">


            </div>
            <div role="tabpanel" class="tab-pane" id="manage_users">


            </div>
            <div role="tabpanel" class="tab-pane" id="billing">


            </div>
            <div role="tabpanel" class="tab-pane" id="listing_default">

            </div>

        </div>

    </div>
</section>
@section scripts {
    <!--Javascript goes here-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="javascripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="javascripts/global.js" type="text/javascript"></script>
    <script src="javascripts/wow.min.js" type="text/javascript"></script>
    <script src="javascripts/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script>
        new WOW().init();
    </script>
    <script>
        $(document).ready(function () {
            $("#listing_date, #status_change_date").datepicker({
                todayHighlight: true,

            });
        });
    </script>
    <script src="~/Scripts/jquery-2.1.3.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '/Settings/_Profile', // The method name + paramater
                success: function (data) {
                    $('#user_info').html(data); // This should be an empty div where you can inject your new html (the partial view)
                }
            });
        });

        $("ul.vertival-tabs").on("click", "li", function () {
            var tabId = $(this).find("a").attr('href');


            if (tabId == "#user_info") {

                $.ajax({
                    url: '/Settings/_Profile', // The method name + paramater
                    success: function (data) {
                        $('#user_info').html(data); // This should be an empty div where you can inject your new html (the partial view)
                    }
                });
            }
            else if (tabId == "#manage_users") {

                $.ajax({
                    url: '/Settings/_ManageUsers', // The method name + paramater
                    success: function (data) {
                        $('#manage_users').html(data); // This should be an empty div where you can inject your new html (the partial view)
                    }
                });
            }
            else if (tabId == "#billing") {
                $.ajax({
                    url: '/Settings/_Billing', // The method name + paramater
                    success: function (data) {
                        $('#billing').html(data); // This should be an empty div where you can inject your new html (the partial view)
                    }
                });
            }
            else if (tabId == "#listing_default") {
                $.ajax({
                    url: '/Settings/_ListingDefaults', // The method name + paramater
                    success: function (data) {
                        $('#listing_default').html(data); // This should be an empty div where you can inject your new html (the partial view)
                    }
                });
            }

        });

    </script>
}

Offer/Offer/Views/Settings/_ListingDefaults.cshtml
<div class="col-md-12">
    
    <div class="col-md-5 col-xs-12  padd-v-40">

        <div class="boxesPadding boxesPadding_full no-padd">
            <div class="row-fluid pull-right editable_mode">
                <a href="#">
                    <i class="material-icons icon_has_topic">edit</i><span class="topic_has_icon">Edit</span>
                </a>
            </div>
            <h4 class="boxesTopic">
                <i class="material-icons icon_has_topic">sort</i>
                <span class="topic_has_icon">Lisiting Status</span>
            </h4>
            <hr>
            <div class="row boxesParagraph">
                <div class="col-md-12 col-xs-12">

                    <div class="">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="active">Active</option>
                                                <option value="in_escrow">In Escrow</option>
                                                <option value="closed">Closed</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>

                <div class="col-md-12 col-xs-12">

                    <div class="">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="active">Active</option>
                                                <option value="in_escrow">In Escrow</option>
                                                <option value="closed">Closed</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>

                <div class="col-md-12 col-xs-12">

                    <div class="">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="active">Active</option>
                                                <option value="in_escrow">In Escrow</option>
                                                <option value="closed">Closed</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>

            </div>

            <div class="row-fluid call_to_action bdr-none padd-h-10">
                <div class="text-center">
                    <button class="btn ctaBtn btn_mainBlue cancel_btn">Cancel</button>
                    <button class="btn ctaBtn btn_mainBlue save_btn">Save</button>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-7 col-xs-12  padd-v-40">
        <div class="boxesPadding boxesPadding_full no-padd">
            <h4 class="boxesTopic">
                <i class="material-icons icon_has_topic">sort</i>
                <span class="topic_has_icon">Offer Instructions</span>
            </h4>
            <hr>
            <div class="row padd-v-30 padd-h-40">
                <div class="col-md-12 col-xs-12 boxesPadding_full colordarkGrey padd-v-15">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
            </div>

            <div class="form-group move_down_group full_width padd-v-10 padd-h-40">
                <div class="input-group">
                    <input id="sameListing" class="checkbox-custom" name="sameListing" type="checkbox" required="required">
                    <label for="sameListing" class="checkbox-custom-label colordarkGrey">Receive tet notifications of new offers</label>
                </div>
            </div>
        </div>

    </div>
</div>

Offer/Offer/Views/Settings/_ManageUsers.cshtml
<div class="col-md-12 ">
    <div class="padd-v-40">
        <div class="row-fluid pull-right editable_mode">
            <a href="#">
                <i class="material-icons icon_has_topic">edit</i><span class="topic_has_icon">Edit</span>
            </a>
        </div>

        <div class="boxesPadding">
            <h4 class="boxesTopic">
                <i class="material-icons icon_has_topic">account_circle</i>
                <span class="topic_has_icon">Manage Users</span>
            </h4>
            <hr>
            <div class="boxesParagraph">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group">
                            <div class="input-group full_width">
                                <input type="text" class="form-control" id="additionalName" placeholder="Full Name" value="Starr Hinojos" required="required" maxlength="100">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-4">
                        <div class="form-group ">
                            <div class="input-group full_width">
                                <input type="email" class="form-control" id="additionaluserEmail" placeholder="Email" value="starhinojos@gmail.com" required="required" maxlength="13">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4  col-sm-4">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="read_only">Read Only</option>
                                                <option value="full_access">Full Accress</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group">
                            <div class="input-group full_width">
                                <input type="text" class="form-control" id="additionalName" placeholder="Full Name" value="Todd Moeller" required="required" maxlength="100">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-4">
                        <div class="form-group ">
                            <div class="input-group full_width">
                                <input type="email" class="form-control" id="additionaluserEmail" placeholder="Email" value="todd@gmail.com" required="required" maxlength="13">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4  col-sm-4">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="read_only">Read Only</option>
                                                <option value="full_access">Full Accress</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group">
                            <div class="input-group full_width">
                                <input type="text" class="form-control" id="additionalName" placeholder="Full Name" required="required" maxlength="100">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-4">
                        <div class="form-group ">
                            <div class="input-group full_width">
                                <input type="email" class="form-control" id="additionaluserEmail" placeholder="Email" required="required" maxlength="13">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4  col-sm-4">
                        <form class="address_form">
                            <div class="row form-group full_width">
                                <div class="col-xs-10">
                                    <ul>
                                        <li>
                                            <select id="statusFilter" class="form-control">
                                                <option value="read_only">Read Only</option>
                                                <option value="full_access">Full Accress</option>

                                            </select>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-2 no-padd">
                                    <button class="btn ctaBtn  cancel_btn fs-20 padd-5 line-height"><i class="material-icons">delete_forever</i></button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
        <div class="row-fluid call_to_action">
            <a href="#" class="">Change Password</a>
            <div class="right">
                <button class="btn ctaBtn btn_mainBlue cancel_btn">Cancel</button>
                <button class="btn ctaBtn btn_mainBlue save_btn">Save</button>
            </div>
        </div>
    </div>
</div>