Offer/Offer/Models/Listing/DetailModel.cs
using Offer.Models.Offer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Listing
{
    public class DetailModel
    {
        public int ListingId { get; set; }
        public string ListingAgent { get; set; }
        public string AgentEmail { get; set; }
        public string AgentPhone { get; set; }
        public string ListingStatus { get; set; }
        public string ListingStatusCode { get; set; }
        public string StreetAddress { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        public string PostalCode { get; set; }

        public string FormattedAddress { get; set; }

        public int ListPrice { get; set; }

        public string FormattedListPrice { get; set; }

        public DateTime? ListDate { get; set; }

        public DateTime? ExpirationDate { get; set; }
        public string MlsUrl { get; set; }

        public string PublicUrl { get; set; }

        public string FormattedListDate { get; set; }
        public string UniqueId { get; set; }
        public string OfferInstructions { get; set; }
        public OfferGroupSearchModel OfferGroups { get; set; }
        public byte[] PropertyImage { get; set; }
    }
}

Offer/Offer/Models/Listing/NewListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Offer.Models.Listing
{
    public class NewListingModel
    {
        public string Address { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        public string PostalCode { get; set; }

        public string MlsNumber { get; set; }

        public string SellerFirstname { get; set; }
        public string SellerLastname { get; set; }
        public string SellerPhone { get; set; }
        public string SellerEmail { get; set; }
        public string SellerAddress { get; set; }
        public string SellerCity { get; set; }
        public string SellerState { get; set; }
        public string SellerPincode { get; set; }

        public DateTime? ListDate { get; set; }
        public int? ListAmount { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string OfferInstruction { get; set; }
    }
}

Offer/Offer/Models/Listing/SearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Offer.Models.Offer;

namespace Offer.Models.Listing
{
    public class SearchModel
    {
        public List<ListingGridItem> ListingItems { get; set; }
    }

    public class ListingGridItem
    {
        public int ListingId { get; set; }
        public string Address { get; set; }
        public int ListAmount { get; set; }
        public DateTime? ListDate { get; set; }
        public string SellerNames { get; set; }
    //Newly Added Fields
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string MlsNumber { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public string Status_LookupCode { get; set; }
        public bool IsDeleted { get; set; }       
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public OfferGroupSearchModel OfferGroups { get; set; }
        public byte[] PropertyImage { get; set; }

    }
}

Offer/Offer/Controllers/ListingController.cs
using Offer.Api;

using Offer.Communication;
using Offer.Data;
using Offer.Logic;
using Offer.Models.Listing;
using Offer.Models.Offer;
using Offer.Models.Seller;
using Offer.Models.Settings;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
namespace OfferManagement.Mvc.Controllers
{  
    public class ListingController : Controller
    {
        AttachmentService attchser = new AttachmentService();
        OfferApiController api = new OfferApiController();
        #region ListingDetail
        // GET: Listing
        public ActionResult Search()
        {
            ViewBag.StatusResult = api.GetListingStatus();
            List<Listing> listings = api.SearchListings();
            SearchModel model = new SearchModel();
            model.ListingItems = new List<ListingGridItem>();
            foreach (Listing listing in listings)
            {
                model.ListingItems.Add(new ListingGridItem
                {
                    Address = listing.Address,
                    ListingId = listing.ListingId,
                    ListAmount = 450000
                });
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {
            DatabaseRepository<Listing> dblisting = new DatabaseRepository<Listing>();
            var listing = (from a in dblisting.Table
                           where a.Address.Contains(prefix) || a.State.Contains(prefix) || a.City.Contains(prefix)
                           select new
                           {
                               label = a.Address + " " + a.City + " " + a.State,
                               val = a.ListingId
                           }).ToList();

            return Json(listing);
        }
        //Search Result 7-SEP-16
        public PartialViewResult _SearchResult(string SearchType, string Address, string Status)
        {
            ViewBag.StatusResult = api.GetListingStatus();
            List<Listing> listings;
            if (SearchType == "Address")
            {
                listings = api.GetListingByAddress(Address);
            }
            else if (SearchType == "Status")
            {
                if (Status == "all")
                {
                    listings = api.SearchListings();
                }
                else
                {
                    List<Listing> ls = new List<Listing>();
                    string[] ListStatus = Status.Split(',');
                    foreach (var item in ListStatus)
                    {
                        var result = api.GetListingByStatus(item);
                        foreach (var data in result)
                        {
                            ls.Add(new Listing
                            {
                                Address = data.Address,
                                ListingId = data.ListingId,
                                ListAmount = Convert.ToInt32(data.ListAmount),
                                ListDate = data.ListDate,
                                City = data.City,
                                PostalCode = data.PostalCode,
                                State = data.State,
                                Status_LookupCode = data.Status_LookupCode,
                            });
                        }
                    }
                    listings = ls;
                    //listings = this.ListingService.ListingSearchByStatus(Status);
                }
            }
            else
            {
                listings = api.SearchListings();
            }
            SearchModel model = new SearchModel();
            model.ListingItems = new List<ListingGridItem>();
            foreach (Listing listing in listings)
            {
                OfferGroupSearchModel offerGroupSearchModel = new OfferGroupSearchModel();
                List<OfferGroupSummary> offerGroups = api.OfferGroupSummarySearch(listing.ListingId);
                foreach (OfferGroupSummary offerGroup in offerGroups)
                {
                    offerGroupSearchModel.OfferGroupItems.Add(new OfferGroupGridItem()
                    {
                        AgentEmail = offerGroup.AgentEmail,
                        AgentFirstname = offerGroup.AgentFirstname,
                        AgentLastname = offerGroup.AgentLastname,
                        BuyerFirstname = offerGroup.BuyerFirstname,
                        BuyerLastname = offerGroup.BuyerLastname,
                        InternalNote = offerGroup.InternalNote,
                        //LoanType = offerGroup.LoanType != null ? offerGroup.LoanType.Value : "",
                        OfferAmount = offerGroup.OfferAmount,
                        OfferDate = offerGroup.OfferDate,
                        CounterInternalNote = offerGroup.CounterInternalNote,
                        // CounterLoanType = offerGroup.CounterLoanType != null ? offerGroup.CounterLoanType.Value : "",
                        CounterOfferAmount = offerGroup.CounterOfferAmount,
                        CounterOfferDate = offerGroup.CounterOfferDate,
                        CounterOfferId = offerGroup.CounterOfferId,
                        OfferId = offerGroup.OfferId
                    });
                }
                model.ListingItems.Add(new ListingGridItem
                {
                    Address = listing.Address,
                    ListingId = listing.ListingId,
                    ListAmount = Convert.ToInt32(listing.ListAmount),
                    ListDate = listing.ListDate,
                    City = listing.City,
                    PostalCode = listing.PostalCode,
                    State = listing.State,
                    OfferGroups = offerGroupSearchModel,
                    Status_LookupCode = listing.Status_LookupCode,
                });
            }
            return PartialView(model.ListingItems);
        }
        //Default List 7-SEP-16
        public PartialViewResult _DisplayAll()
        {
            ViewBag.StatusResult = api.GetListingStatus();
            List<Listing> listings = api.SearchListings();
            SearchModel model = new SearchModel();
            model.ListingItems = new List<ListingGridItem>();
            foreach (Listing listing in listings)
            {
                OfferGroupSearchModel offerGroupSearchModel = new OfferGroupSearchModel();
                List<OfferGroupSummary> offerGroups = api.OfferGroupSummarySearch(listing.ListingId);
                foreach (OfferGroupSummary offerGroup in offerGroups)
                {
                    offerGroupSearchModel.OfferGroupItems.Add(new OfferGroupGridItem()
                    {
                        AgentEmail = offerGroup.AgentEmail,
                        AgentFirstname = offerGroup.AgentFirstname,
                        AgentLastname = offerGroup.AgentLastname,
                        BuyerFirstname = offerGroup.BuyerFirstname,
                        BuyerLastname = offerGroup.BuyerLastname,
                        InternalNote = offerGroup.InternalNote,
                        // LoanType = offerGroup.LoanType != null ? offerGroup.LoanType.Value : "",
                        OfferAmount = offerGroup.OfferAmount,
                        OfferDate = offerGroup.OfferDate,
                        CounterInternalNote = offerGroup.CounterInternalNote,
                        // CounterLoanType = offerGroup.CounterLoanType != null ? offerGroup.CounterLoanType.Value : "",
                        CounterOfferAmount = offerGroup.CounterOfferAmount,
                        CounterOfferDate = offerGroup.CounterOfferDate,
                        CounterOfferId = offerGroup.CounterOfferId,
                        OfferId = offerGroup.OfferId
                    });
                }

                var attchments = api.GetListingAttachment(listing.ListingId);
                byte[] tempfile;
                if (attchments != null)
                {

                    tempfile = attchser.GetTemporaryFile(attchments.LocalFilename);
                }
                else
                { //Demo Image

                    tempfile = attchser.GetTemporaryFile("49bfb058-801b-4a30-9c6c-0359c8dcc23f");
                }

                model.ListingItems.Add(new ListingGridItem
                {
                    Address = listing.Address,
                    ListingId = listing.ListingId,
                    ListAmount = Convert.ToInt32(listing.ListAmount),
                    ListDate = listing.ListDate,
                    City = listing.City,
                    PostalCode = listing.PostalCode,
                    State = listing.State,
                    OfferGroups = offerGroupSearchModel,
                    Status_LookupCode = listing.Status_LookupCode,
                    PropertyImage = tempfile
                });


            }
            return PartialView(model.ListingItems);
        }
        //Edit Status 8-SEP-16
        public void ChangeStatus(int ListId, string Status)
        {
            api.ChangeListingStatus(ListId, Status);
        }
        public ActionResult Detail(int id)
        {

            ViewBag.state = api.GetAllStates();
            ViewBag.StatusResult = api.GetListingStatus();
            Listing listing = api.GetListingById(id);

            User agent = api.GetUserDetail(Convert.ToInt32(listing.CreatedByUserId));
            DetailModel model = new DetailModel();
            model.ListingId = listing.ListingId;
            model.StreetAddress = listing.Address;
            model.City = listing.City;
            model.State = listing.State;
            model.PostalCode = listing.PostalCode;
            model.AgentEmail = agent.Email;
            model.AgentPhone = agent.PhoneNumber;

Offer/Offer/Views/Listing/EditSeller.cshtml
@model  DubTech.Framework.Ef.Seller
@{
    var base64 = Convert.ToBase64String(ViewBag.sellerimage);
    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    Layout = null;
    }
@*New Design*@
@using (Html.BeginForm("EditSeller", "Listing", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
{  @Html.HiddenFor(m => m.SellerId)
    @Html.HiddenFor(m => m.ListingId)
    <div class="col-sm-6 text-center col-xs-12 marg-t-15" id="edit_one">
        <div class="saller_img_edit">
            <img src="@imgSrc" alt="">
            <a href="javascript:void(0);" class="btn_uploard">
                <span for="dev">change</span>
                <input id="dev" type="file" name="sellerpic" />
            </a>
        </div>

        <div class="saller_name_edit padd-h-10 padd-v-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control required", placeholder = "First Name" })

                </div>
            </div>
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control required", placeholder = "Last Name" })
                </div>
            </div>
        </div>

        <div class="col-md-12 col-xs-12  bdr-tp-1 padd-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control required", placeholder = "Phone" })
                </div>
            </div>

            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control required", placeholder = "Email" })
                </div>
            </div>

        </div>
        <div class="col-md-12 col-xs-12  padd-10">
            <div class="form-group">
                <div class="input-group full_width">
                    @Html.TextAreaFor(m => m.Note, new { @class = "form-control", placeholder = "Seller's Note" })
                </div>
            </div>

        </div>

        <div class="col-md-12 col-xs-12  padd-v-10">

            <button type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn" id="submitseller">Save Changes</button>
            <button class="btn ctaBtn btn_mainBlue cancel_btn close_me" type="button" onclick="CancelEdit()" >Cancel</button>
            
        </div>
    </div>
}





@*Old Design*@
    @*
            @using (Html.BeginForm("EditSeller", "Listing", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
    {<div class="row-fluid setup-content" id="step-1">
            <div id="sellersInformation" class="row-fluid">
                <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">

                    <div class="boxesPadding">
                        <h4 class="boxesTopic">
                            <i class="material-icons icon_has_topic">account_circle</i>
                            <span class="topic_has_icon">Sellers Information</span>
                        </h4>
                        <hr>
                        <div class="row boxesParagraph">
                            <div class="col-md-12">
                                @Html.HiddenFor(m => m.SellerId)
                                @Html.HiddenFor(m => m.ListingId)
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group full_width">
                                                @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control required", placeholder = "First Name" })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">

                                                @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control required", placeholder = "Last Name" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group full_width">
                                    <div class="input-group">
                                        @Html.TextAreaFor(m => m.Address, new { @class = "form-control required", placeholder = "Address" })

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 col-sm-4 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">
                                                @Html.TextBoxFor(m => m.State, new { @class = "form-control required", placeholder = "State" })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">
                                                @Html.TextBoxFor(m => m.City, new { @class = "form-control required", placeholder = "City" })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">

                                                @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control required", placeholder = "Postal Code" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">
                                                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control required", placeholder = "Phone" })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 half_padding">
                                        <div class="form-group full_width">
                                            <div class="input-group">

                                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control required", placeholder = "Email" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row-fluid call_to_action">
                        <div class="right">
                            <a onclick="CancelEdit()" class="btn ctaBtn btn_mainBlue cancel_btn">Cancel</a>
                            <button type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn" id="submitseller">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>}*@

Offer/Offer/Views/Listing/NewSeller.cshtml
@model  Offer.Models.Seller.NewSellerModel
@{
    Layout = null;
    int ListId = Convert.ToInt32(TempData["ListingID"]);
}
@*<script src="~/Scripts/validation.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(documemt).ready(function () {
        $('#ListingId').val(@ListId);
    });
</script>
@*<script>
        $('#submitseller').click(function ()
        {
            alert('hi');
            $.ajax({
                type: "POST",
                url: "Listing/NewSeller",
                data: $("FRM").serialize(),
                dataType:"json",
                success: function(resultData){
                    alert("Save Complete");
                    $('#sellistddiv').load('/Listing/SellersList?ListingID=' +  @ListId;
                }
            });
    </script>*@
@using (Html.BeginForm("NewSeller", "Listing", FormMethod.Post, new { id = "FRM", enctype = "multipart/form-data" }))
{    @Html.HiddenFor(m => m.ListingId, new { id = "ListingId" })
    @Html.ValidationSummary(true)
    <div class="col-sm-6 text-center col-xs-12 marg-t-15">
        <div class="boxesPadding_full no-padd pull-left">
          
                <div class="saller_img_edit">
                    <img src="~/Content/images/demo/user.jpgc" alt="">
                    <a href="javascript:void(0);" class="btn_uploard">
                        <span for="dev">change</span>
                        <input id="dev" type="file" name="sellerpic" />
                    </a>
                </div>
            <div class="saller_name_edit padd-h-10 padd-v-10">
                <div class="form-group">
                    <div class="input-group half_padding">
                        @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control required", placeholder = "First Name"})
                        @Html.ValidationMessageFor(m => m.Firstname)
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group half_padding">
                        @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control required", placeholder = "Last Name" })
                        @Html.ValidationMessageFor(m => m.Lastname)
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-xs-12  padd-10">

                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = "Phone"})
                        @Html.ValidationMessageFor(m => m.Phone)
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-xs-12  padd-10">
                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                </div>

            </div>
            <div class="col-md-12 col-xs-12  padd-10">
                <div class="form-group">
                    <div class="input-group full_width">
                        @Html.TextAreaFor(m => m.Note, new { @class = "form-control", placeholder = "Seller's Note"})
                    </div>
                </div>

            </div>
           

           
          
            <div class="col-md-12 col-xs-12  padd-v-10">

                <button type="submit" class="btn ctaBtn btn_mainBlue nextBtn save_btn" id="submitseller">Save Changes</button>
                <button class="btn ctaBtn btn_mainBlue cancel_btn close_me" onclick="cancelNewseller()">Cancel</button>
            </div>
        </div>
    </div>
}





       

Offer/Offer/Views/Listing/SellersList.cshtml
@model List<Offer.Models.Seller.SellerGridItem>
@*<button type="button" onclick="NewSeller()" class="btn btn-outline btn-primary btn-sm">New Seller</button>*@
<div class="col-sm-12">
    <button class="btn ctaBtn btn_mainBlue  border_btn col-md-3 col-xs-12 no-padd txt-upper text-center" onclick="NewSeller()"><i class="material-icons icon_has_topic fs-20">group_add</i><span class="topic_has_icon">New Seller</span></button>
</div>

    @{
        int i = 1;
    }
    @foreach (var item in Model)
    {
        <div class="col-sm-6 text-center col-xs-12 marg-t-15" id="seller-@item.SellerId">
            <div class="boxesPadding_full no-padd pull-left">
                @{
        var base64 = Convert.ToBase64String(item.SellerImage);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }
                <div class="no-padd pull-left edit ">
                    <div class="saller_img">
                        <img src="@imgSrc" alt="">

                    </div>
                    <div class="saller_name">
                        <h4 class="pull-left padd-v-10 padd-h-10 full-width ">
                            @item.Firstname @item.Lastname
                        </h4>
                    </div>
                    <div class="edit-del padd-v-20 ">
                        <span>
                            <a href="javascript:void(0);" id="edit_one" onclick="Editseller(@item.SellerId)">
                                <i class="material-icons colordarkGrey" >edit</i>
                            </a>
                        </span>
                        <span>
                            <a href="javascript:void(0);" onclick="DeleteSeller(@item.SellerId)">
                                <i class="material-icons colordarkGrey">delete</i>
                            </a>
                        </span>
                    </div>
                </div>
                <div class="col-md-12 col-xs-12  bdr-tp-1  padd-v-5">
                    <h4><a href="/Listing/Detail/@item.ListingId">@item.Address</a></h4>
                    <p>@item.City, @item.State @item.PostalCode</p>
                </div>
                    <div class="col-md-12 col-xs-12  bdr-tp-1  padd-v-5">
                        @item.Phone
                    </div>
                    <div class="col-md-12 col-xs-12  padd-v-5">
                        @item.Email
                    </div>

                    


                    <div class="col-md-12 col-xs-12  padd-v-5">
                        <p>@item.Note</p>
                    </div>

                    <div class="col-md-12 col-xs-12  padd-v-10">
                        <button class="btn ctaBtn btn_mainBlue save_btn">Seller #@i</button>
                    </div>

                </div></div>i++;
        }

        @*<div class="table-responsive">
                <table id="listingsellerTable" class="table table-bordered" style="width:100% !important">
                    <thead>
                        <tr class="btn_blue">
                            <th class="text-center">First Name</th>
                            <th class="text-center">Last Name</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Phone</th>
                            <th class="text-center">Address</th>
                            <th class="text-center">State</th>
                            <th class="text-center">City</th>
                            <th class="text-center">Postal Code</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                    {
                    <tr class="text-danger">
                        <td>@item.Firstname</td>
                        <td>@item.Lastname </td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Address</td>
                        <td>@item.State</td>
                        <td>@item.City</td>
                        <td>@item.PostalCode</td>
                        <td><a href="/Listing/EditSeller?SellerId=@item.SellerId">Edit</a><a href="/Listing/DeleteSeller?SellerId=@item.SellerId">Delete</a></td>
                    </tr>
                    }

                    </tbody>
                </table>
            </div>*@




        <script>
            $(document).ready(function () {

                $('#listingsellerTable').DataTable();

            });



        </script>